[package]
name = "IrieOS"
version = "0.1.0"
edition = "2021"
authors = ["riccioadami@gmail.com"]

[dependencies]
bootloader = "0.11.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"